### ISSUE TITLE
Update ctrulib

### ISSUE THREAD

**Issue by handsomematt** [MrJPGames/Mastermind-3DS#1]
your current version is incredibly outdated and lacks a lot of features and bug fixes.

**Comment by MrJPGames** [comment]
Though non of the bugs seem to have caused any issues in with my homebrew I will update my ctrulib, (and change things to be compatible eg. gfxInit() to gfxInitDefault()). I was aware of this but was just too lazy to update as I didn't need the update.

**Comment by handsomematt** [comment]
I mean you don't have to, but it'd be nice if you did. These (this and 2048) could be really good example projects of what 3DS homebrew is capable of.

**Comment by MrJPGames** [comment]
I will update soon, currently my work PC is updating windows... So yeah, expect a small update to reflect changes made in the most up-to-date version of ctrulib soon.

**Comment by MrJPGames** [comment]
Just updated the repo, now all code works with latest version of ctrulib included with devkitPro.
